# Ryan Brooks: This Service exposes the frontend Deployment through a NodePort for browser access.
apiVersion: v1
kind: Service
metadata:
  name: {{ include "swe645-ha3.fullname" . }}-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: {{ include "swe645-ha3.fullname" . }}-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: 80
      nodePort: {{ .Values.frontend.service.nodePort }}
